### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by MattCatz** [japaric/stm32f30x#18]
The documentation link in the README does go anywhere meaningful.

**Comment by caemor** [comment]
Thats a problem of doc.rs atm which is still unfixed see https://github.com/onur/docs.rs/issues/226

You can either use cargo doc in your project to build the documentation locally or go to https://docs.rs/stm32f30x/0.7.0/stm32f30x/ to view the lasted documentation that's available on doc.rs

**Comment by MattCatz** [comment]
Thanks for the update!

**Comment by caemor** [comment]
Issue should be resolved now since the link is working now

**Comment by MattCatz** [comment]
Thanks so much for the follow up!
