### ISSUE TITLE
Regenerate using svd2rust 0.14.x

### ISSUE THREAD

**Issue by simonvandel** [japaric/stm32f30x#19]
As mentioned in the [docs](https://japaric.github.io/cortex-m-rtfm/book/by-example/app.html) for cortex-m-rtfm, it will only work for a device crate generated using svd2rust 0.14.x. 

What would it take to do this?

**Comment by japaric** [comment]
> What would it take to do this?

svd2rust 0.14.x has to be released first :smile:

**Comment by caemor** [comment]
The crate was generated with svd2rust 0.14.x for it's 0.8 release so this issue might be solved.
